import logging
import os
from typing import Annotated

from pydantic import AliasChoices, BaseModel, Field, computed_field
from pydantic_settings import BaseSettings, SettingsConfigDict

logger = logging.getLogger(__name__)

class WebsocketsConfig(BaseModel):
    ws_hostname: str = Field(
        default="localhost:8080",
        description="The hostname of the server serving standard websocket connections."
    )
    liveapi_proxy_hostname: str = Field(
        default="localhost:8080",
        description="The hostname of the server proxying websocket connections to Gemini LiveAPI."
    )

class OAuthConfig(BaseModel):
    enabled: bool = Field(
        default=True,
        description="Whether to validate the Authorization bearer token. Disable for local testing.",
    )
    verify_signature: bool = Field(
        default=True,
        description="Whether to verify the token signature against the Entra JWKS.",
    )

class GoogleCloudStorageConfig(BaseModel):
    bucket_id: str = Field(
        default="bkt-d-us-genai-aitrainer-recordings-z1f2",
        description="The ID of the GCS bucket used to store application BLOBs."
    )
    file_signed_url_sa: str = Field(
        default="sa-d-g-genai-sign@gcp-genai-3-d-aitrainer-wq9z.iam.gserviceaccount.com",
        description="Service account email used for generating signed URLs."
    )

class FirestoreConfig(BaseModel):
    database_id: str = Field(
        default="fs-d-genai-aitrainer-appdata-h366",
        description="The ID of the Firestore database used to store application data."
    )

class GenAIConfig(BaseModel):
    model_name: str = Field(
        default="gemini-2.5-flash",
        description="Base model name used to generate prompts output."
    )
    location: str = Field(
        default="us-central1",
        description="GCP location/region for Vertex AI services."
    )

class GoogleCloudPlatformConfig(BaseModel):
    project_number: Annotated[str, Field(
        default="668181095076",
    )]
    project_id: Annotated[str, Field(
        default="gcp-genai-3-d-aitrainer-wq9z"
    )]

    firestore_config: Annotated[FirestoreConfig, Field(
        default_factory=FirestoreConfig,
        description="Configuration for the usage of Firestore.",
        validation_alias=AliasChoices("firestore", "firestore_config")
    )]

    gcs_config: Annotated[GoogleCloudStorageConfig, Field(
        default_factory=GoogleCloudStorageConfig,
        description="Configuration for the usage of Google Cloud Storage.",
        validation_alias=AliasChoices("gcs", "gcs_config")
    )]

    genai_config: Annotated[GenAIConfig, Field(
        default_factory=GenAIConfig,
        description="Configuration for the usage of Gen AI.",
        validation_alias=AliasChoices("genai", "genai_config")
    )]

class JWTConfig(BaseModel):
    aitr_jwt_key: Annotated[str, Field(
        default="aitr_token",
        description="Key for the HttpOnly Cookie used to store the application JWT."
    )]

    aitr_jwt_signing_algorithm: Annotated[str, Field(
        default="HS256",
        description="Algorithm used to sign and verify a JWT generated by this application."
    )]

    aitr_jwt_signing_secret: Annotated[str, Field(
        default="gExADEhP7KwsmV+SuS1EQ/0+/J3PaY0Oiio7yc3AvBc=",
        description="Secret key used in conjunction with `aitr_jwt_signing_algorithm` to sign and verify a JWT generated by this application."
    )]

class EntraConfig(BaseModel):
    """Configuration for validating Microsoft Entra (Azure AD) access tokens."""

    enabled: Annotated[bool, Field(
        default=True,
        description="Whether to validate the Authorization bearer token. Disable for local testing.",
    )]

    tenant_id: Annotated[str, Field(
        default="common",
        description="Microsoft Entra tenant ID (directory ID).",
    )]

    audience: Annotated[str, Field(
        default="",
        description="Expected token audience (the application/client ID or API App ID URI).",
    )]

    jwks_uri: Annotated[str, Field(
        default="",
        description="Override for the JWKS URI. If empty, it is derived from tenant_id.",
    )]

    verify_signature: Annotated[bool, Field(
        default=True,
        description="Whether to verify the token signature against the Entra JWKS.",
    )]

    @computed_field
    @property
    def openid_config_url(self) -> str:
        return f"https://login.microsoftonline.com/{self.tenant_id}/v2.0/.well-known/openid-configuration"

    @computed_field
    @property
    def default_jwks_uri(self) -> str:
        if self.jwks_uri:
            return self.jwks_uri
        return f"https://login.microsoftonline.com/{self.tenant_id}/discovery/v2.0/keys"

    @computed_field
    @property
    def issuer(self) -> str:
        return f"https://login.microsoftonline.com/{self.tenant_id}/v2.0"


class CacheConfig(BaseModel):
    prefix: Annotated[str, Field(
        default="aitrainer-cache"
    )]

    course_list_namespace: Annotated[str, Field(
        default="course_list"
    )]

    course_list_ttl_seconds: Annotated[int, Field(
        default=3600,
        gt=0
    )]

    course_list_fetch_concurrency: Annotated[int, Field(
        default=50,
        gt=0
    )]


class GitLabConfig(BaseModel):
    """Configuration for GitLab API integration."""

    url: str = Field(
        default="https://gitlab.com",
        description="GitLab instance URL."
    )
    token: str = Field(
        default="",
        description="GitLab Personal Access Token (PAT)."
    )

class Config(BaseSettings):
    model_config = SettingsConfigDict(
        env_nested_delimiter="__",
        env_file_encoding="utf-8"
    )

    cursor_secret_key: str = Field(
        default="xK8vD2mP9nQ5rS6tU7vW8xY9zA0bC1dE2fF3gG4hH5i=",
        description="Secret key for cursor encryption"
    )
    
    log_level: str = Field("info", description="Global logging level")

    gcp_config: Annotated[GoogleCloudPlatformConfig, Field(
        default_factory=GoogleCloudPlatformConfig,
        description="Configuration for the usage of Google Cloud Platform.",
        validation_alias=AliasChoices("gcp", "gcp_config")
    )]

    genai_config: Annotated[GenAIConfig, Field(
        default_factory=GenAIConfig,
        description="Configuration for the usage of Gen AI.",
        validation_alias=AliasChoices("genai", "genai_config")
    )]

    websockets_config: Annotated[WebsocketsConfig, Field(
        default_factory=WebsocketsConfig,
        description="Configuration for the usage of websockets.",
        validation_alias=AliasChoices("ws", "websockets", "websockets_config")
    )]

    oauth_config: Annotated[OAuthConfig, Field(
        default_factory=OAuthConfig,
        description="Configuration for the usage of OAuth.",
        validation_alias=AliasChoices("oauth", "oauth_config")
    )]

    jwt_config: Annotated[JWTConfig, Field(
        default_factory=JWTConfig,
        description="Configuration for the signing and verifying of JWTs created by this application.",
        validation_alias=AliasChoices("jwt", "jwt_config")
    )]

    cache_config: Annotated[CacheConfig, Field(
        default_factory=CacheConfig,
        description="Configuration for the usage of caching features",
        validation_alias=AliasChoices("cache", "cache_config")
    )]

    entra_config: Annotated[EntraConfig, Field(
        default_factory=EntraConfig,
        description="Configuration for validating Microsoft Entra access tokens.",
        validation_alias=AliasChoices("entra", "entra_config", "azure_ad")
    )]

    gitlab_config: Annotated[GitLabConfig, Field(
        default_factory=GitLabConfig,
        description="Configuration for GitLab API integration.",
        validation_alias=AliasChoices("gitlab", "gitlab_config")
    )]


def load_config() -> Config:
    try:
        logger.info(f"K_SERVICE: {os.environ.get('K_SERVICE')}")
        K_SERVICE: str = os.environ.get("K_SERVICE", os.environ.get("JOB_ENV", "local"))
        logger.info(f"K_SERVICE JOB_ENV: {K_SERVICE}")
        config_file_dir = os.path.dirname(os.path.abspath(__file__))
        logger.info(f"config_file_dir: {config_file_dir}")
        return Config(_env_file=os.path.join(config_file_dir, f".env.{K_SERVICE}"))
    except Exception as e:
        print(f"Failed to load configuration: {e}")

def load_gcp_config() -> GoogleCloudPlatformConfig:
    config = load_config()
    return config.gcp_config

def load_cache_config() -> CacheConfig:
    config = load_config()
    return config.cache_config

def load_entra_config() -> EntraConfig:
    config = load_config()
    entra = config.entra_config
    # The OAUTH__ env keys (oauth_config) drive enable/verify for local dev;
    # overlay them onto the Entra config used by the auth dependency.
    oauth = config.oauth_config
    return entra.model_copy(update={
        "enabled": oauth.enabled,
        "verify_signature": oauth.verify_signature,
    })

def load_gitlab_config() -> GitLabConfig:
    config = load_config()
    return config.gitlab_config

